const std = @import("std");
const builtin = @import("builtin");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const t = target.result;
    const is_macos = t.os.tag.isDarwin();
    const is_windows = t.os.tag == .windows;
    const is_posix = !is_windows;

    const zlib_dep = b.dependency("zlib", .{
        .target = target,
        .optimize = optimize,
    });

    const exe = b.addExecutable(.{
        .name = "nasm",
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    exe.root_module.linkLibrary(zlib_dep.artifact("z"));
    exe.link_function_sections = true;
    exe.link_data_sections = true;

    exe.root_module.addIncludePath(b.path("."));
    exe.root_module.addIncludePath(b.path("include"));
    exe.root_module.addIncludePath(b.path("asm"));
    exe.root_module.addIncludePath(b.path("x86"));
    exe.root_module.addIncludePath(b.path("output"));
    exe.root_module.addConfigHeader(b.addConfigHeader(.{
        .style = .blank,
        .include_path = "version.h",
    }, .{
        .NASM_MAJOR_VER = 3,
        .NASM_MINOR_VER = 1,
        .NASM_SUBMINOR_VER = 0,
        .NASM_PATCHLEVEL_VER = 0,
        .NASM_VERSION_ID = 0x03010000,
        .NASM_VER = "3.01",
    }));
    exe.root_module.addConfigHeader(b.addConfigHeader(.{
        .style = .{ .autoconf_undef = b.path("config/config.h.in") },
        .include_path = "config/config.h",
    }, .{
        .ABORT_ON_PANIC = have(optimize == .Debug),
        .AC_APPLE_UNIVERSAL_BUILD = null,
        .CFLAGS_FDATA_SECTIONS = have(exe.link_function_sections),
        .CFLAGS_FFUNCTION_SECTIONS = have(exe.link_data_sections),
        .CFLAGS_FGNU89_INLINE = null,
        .CFLAGS_FNO_COMMON = have(is_macos),
        .CFLAGS_FNO_OMIT_FRAME_POINTER = null,
        .CFLAGS_FSANITIZE_ADDRESS = null,
        .CFLAGS_FSANITIZE_UNDEFINED = null,
        .CFLAGS_FTRIVIAL_AUTO_VAR_INIT_ZERO = null,
        .CFLAGS_FVISIBILITY_HIDDEN = null,
        .CFLAGS_FWRAPV = null,
        .CFLAGS_G3 = null,
        .CFLAGS_GGDB3 = null,
        .CFLAGS_O0 = have(optimize == .Debug),
        .CFLAGS_OG = null,
        .CFLAGS_PEDANTIC = null,
        .CFLAGS_PG = null,
        .CFLAGS_STD_C11 = null,
        .CFLAGS_STD_C17 = null,
        .CFLAGS_STD_C23 = 1,
        .CFLAGS_STD_C99 = null,
        .CFLAGS_U_STRICT_ANSI_ = null,
        .CFLAGS_W = null,
        .CFLAGS_WALL = null,
        .CFLAGS_WERROR = null,
        .CFLAGS_WERROR_COMMENT = null,
        .CFLAGS_WERROR_IMPLICIT = null,
        .CFLAGS_WERROR_MISSING_BRACES = null,
        .CFLAGS_WERROR_MISSING_DECLARATIONS = null,
        .CFLAGS_WERROR_MISSING_PROTOTYPES = null,
        .CFLAGS_WERROR_POINTER_ARITH = null,
        .CFLAGS_WERROR_RETURN_TYPE = null,
        .CFLAGS_WERROR_STRICT_PROTOTYPES = null,
        .CFLAGS_WERROR_TRIGRAPHS = null,
        .CFLAGS_WERROR_UNKNOWN_WARNING_OPTION = null,
        .CFLAGS_WERROR_VLA = null,
        .CFLAGS_WNO_LONG_LONG = null,
        .CFLAGS_WNO_PEDANTIC_MS_FORMAT = null,
        .CFLAGS_WNO_SHIFT_NEGATIVE_VALUE = null,
        .CFLAGS_WNO_STRINGOP_TRUNCATION = null,
        .CFLAGS_WNO_VARIADIC_MACROS = null,
        .CFLAGS_WSUGGEST_ATTRIBUTE_COLD = null,
        .CFLAGS_WSUGGEST_ATTRIBUTE_CONST = null,
        .CFLAGS_WSUGGEST_ATTRIBUTE_FORMAT = null,
        .CFLAGS_WSUGGEST_ATTRIBUTE_MALLOC = null,
        .CFLAGS_WSUGGEST_ATTRIBUTE_NORETURN = null,
        .CFLAGS_WSUGGEST_ATTRIBUTE_PURE = null,
        .CPPFLAGS_WERROR_ATTRIBUTES = null,
        .HAVE_ACCESS = 1,
        .HAVE_ARPA_INET_H = 1,
        .HAVE_BSWAP_16 = null,
        .HAVE_BSWAP_32 = null,
        .HAVE_BSWAP_64 = null,
        .HAVE_BYTESWAP_H = 1,
        .HAVE_CANONICALIZE_FILE_NAME = null,
        .HAVE_CPU_TO_BE16 = null,
        .HAVE_CPU_TO_BE32 = null,
        .HAVE_CPU_TO_BE64 = null,
        .HAVE_CPU_TO_LE16 = null,
        .HAVE_CPU_TO_LE32 = null,
        .HAVE_CPU_TO_LE64 = null,
        .HAVE_DECL_STRCASECMP = have(is_posix),
        .HAVE_DECL_STRICMP = 0,
        .HAVE_DECL_STRLCPY = have(is_posix),
        .HAVE_DECL_STRNCASECMP = have(is_posix),
        .HAVE_DECL_STRNICMP = 0,
        .HAVE_DECL_STRNLEN = have(is_posix),
        .HAVE_DECL_STRRCHRNUL = 0,
        .HAVE_DECL_STRSEP = have(is_posix),
        .HAVE_ENDIAN_H = have(is_posix and !is_macos),
        .HAVE_FACCESSAT = have(is_posix),
        .HAVE_FCNTL_H = have(is_posix),
        .HAVE_FILENO = 1,
        .HAVE_FSEEKO = have(is_posix),
        .HAVE_FSTAT = have(is_posix),
        .HAVE_FTRUNCATE = have(is_posix),
        .HAVE_FUNC_ATTRIBUTE_1_ALLOC_SIZE = 1,
        .HAVE_FUNC_ATTRIBUTE_2_ALLOC_SIZE = 1,
        .HAVE_FUNC_ATTRIBUTE_3_FORMAT = 1,
        .HAVE_FUNC_ATTRIBUTE_COLD = 1,
        .HAVE_FUNC_ATTRIBUTE_CONST = 1,
        .HAVE_FUNC_ATTRIBUTE_ERROR = 1,
        .HAVE_FUNC_ATTRIBUTE_MAYBE_UNUSED = 1,
        .HAVE_FUNC_ATTRIBUTE_MALLOC = 1,
        .HAVE_FUNC_ATTRIBUTE_NORETURN = 1,
        .HAVE_FUNC_ATTRIBUTE_PURE = 1,
        .HAVE_FUNC_ATTRIBUTE_REPRODUCIBLE = 1,
        .HAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL = 1,
        .HAVE_FUNC_ATTRIBUTE_SENTINEL = 1,
        .HAVE_FUNC_ATTRIBUTE_UNSEQUENCED = 1,
        .HAVE_FUNC_ATTRIBUTE_UNUSED = 1,
        .HAVE_FUNC_NAME = 1,
        .HAVE_FUNC_PTR_ATTRIBUTE_1_ALLOC_SIZE = 1,
        .HAVE_FUNC_PTR_ATTRIBUTE_2_ALLOC_SIZE = 1,
        .HAVE_FUNC_PTR_ATTRIBUTE_3_FORMAT = 1,
        .HAVE_FUNC_PTR_ATTRIBUTE_COLD = 1,
        .HAVE_FUNC_PTR_ATTRIBUTE_CONST = 1,
        .HAVE_FUNC_PTR_ATTRIBUTE_MALLOC = 1,
        .HAVE_FUNC_PTR_ATTRIBUTE_MAYBE_UNUSED = 1,
        .HAVE_FUNC_PTR_ATTRIBUTE_NORETURN = 1,
        .HAVE_FUNC_PTR_ATTRIBUTE_PURE = 1,
        .HAVE_FUNC_PTR_ATTRIBUTE_REPRODUCIBLE = 1,
        .HAVE_FUNC_PTR_ATTRIBUTE_RETURNS_NONNULL = 1,
        .HAVE_FUNC_PTR_ATTRIBUTE_SENTINEL = 1,
        .HAVE_FUNC_PTR_ATTRIBUTE_UNSEQUENCED = 1,
        .HAVE_FUNC_PTR_ATTRIBUTE_UNUSED = 1,
        .HAVE_GETGID = have(is_posix),
        .HAVE_GETPAGESIZE = have(is_posix),
        .HAVE_GETRLIMIT = have(is_posix),
        .HAVE_GETUID = have(is_posix),
        .HAVE_HTOBE16 = have(!is_macos and !is_windows),
        .HAVE_HTOBE32 = have(!is_macos and !is_windows),
        .HAVE_HTOBE64 = have(!is_macos and !is_windows),
        .HAVE_HTOLE16 = have(!is_macos and !is_windows),
        .HAVE_HTOLE32 = have(!is_macos and !is_windows),
        .HAVE_HTOLE64 = have(!is_macos and !is_windows),
        .HAVE_HTONL = have(!is_windows),
        .HAVE_HTONQ = have(!is_macos and !is_windows),
        .HAVE_HTONS = have(!is_windows),
        .HAVE_INTRIN_H = have(is_windows),
        .HAVE_INTTYPES_H = 1,
        .HAVE_IO_H = null,
        .HAVE_ISASCII = 1,
        .HAVE_ISCNTRL = 1,
        .HAVE_MACHINE_ENDIAN_H = have(is_macos),
        .HAVE_MEMPCPY = have(is_posix and !is_macos),
        .HAVE_MEMPSET = null,
        .HAVE_MINIX_CONFIG_H = null,
        .HAVE_MMAP = have(is_posix),
        .HAVE_PATHCONF = have(is_posix),
        .HAVE_REALPATH = have(is_posix),
        .HAVE_SNPRINTF = 1,
        .HAVE_STAT = 1,
        .HAVE_STDARG_H = 1,
        .HAVE_STDBIT_H = have(is_posix and !is_macos),
        .HAVE_STDBOOL_H = 1,
        .HAVE_STDC_INLINE = 1,
        .HAVE_STDC_LEADING_ZEROS = have(is_posix and !is_macos),
        .HAVE_STDINT_H = 1,
        .HAVE_STDIO_H = 1,
        .HAVE_STDLIB_H = 1,
        .HAVE_STDNORETURN_H = 1,
        .HAVE_STRCASECMP = have(is_posix),
        .HAVE_STRICMP = have(is_windows),
        .HAVE_STRINGS_H = have(is_posix),
        .HAVE_STRING_H = 1,
        .HAVE_STRLCPY = have(is_posix),
        .HAVE_STRNCASECMP = have(is_posix),
        .HAVE_STRNICMP = have(is_windows),
        .HAVE_STRNLEN = 1,
        .HAVE_STRRCHRNUL = null,
        .HAVE_STRSEP = have(is_posix),
        .HAVE_STRUCT_STAT = 1,
        .HAVE_STRUCT__STATI64 = have(is_windows),
        .HAVE_SYSCONF = have(is_posix),
        .HAVE_SYS_ENDIAN_H = have(is_posix and !is_macos),
        .HAVE_SYS_MMAN_H = have(is_posix),
        .HAVE_SYS_PARAM_H = have(is_macos),
        .HAVE_SYS_RESOURCE_H = have(is_macos),
        .HAVE_SYS_STAT_H = 1,
        .HAVE_SYS_TYPES_H = 1,
        .HAVE_S_ISREG = have(is_posix),
        .HAVE_TYPEOF = 1,
        .HAVE_UINTMAX_T = 1,
        .HAVE_UINTPTR_T = 1,
        .HAVE_UNISTD_H = have(is_posix),
        .HAVE_UNSIGNED_LONG_LONG_INT = 1,
        .HAVE_VARADIC_MACROS_COMMA_HACK = null,
        .HAVE_VARIADIC_MACROS = 1,
        .HAVE_VSNPRINTF = 1,
        .HAVE_WCHAR_H = 1,
        .HAVE__ACCESS = have(is_windows),
        .HAVE__BITSCANREVERSE = have(is_windows),
        .HAVE__BITSCANREVERSE64 = have(is_windows),
        .HAVE__BOOL = 1,
        .HAVE__BYTESWAP_UINT64 = have(is_windows),
        .HAVE__BYTESWAP_ULONG = have(is_windows),
        .HAVE__BYTESWAP_USHORT = have(is_windows),
        .HAVE__CHSIZE = have(is_windows),
        .HAVE__CHSIZE_S = have(is_windows),
        .HAVE__FILENO = have(is_windows),
        .HAVE__FSEEKI64 = have(is_windows),
        .HAVE__FSTATI64 = have(is_windows),
        .HAVE__FULLPATH = have(is_windows),
        .HAVE__STATI64 = have(is_windows),
        .HAVE___BUILTIN_BSWAP16 = 1,
        .HAVE___BUILTIN_BSWAP32 = 1,
        .HAVE___BUILTIN_BSWAP64 = 1,
        .HAVE___BUILTIN_CHOOSE_EXPR = 1,
        .HAVE___BUILTIN_CLZ = 1,
        .HAVE___BUILTIN_CLZLL = 1,
        .HAVE___BUILTIN_CONSTANT_P = 1,
        .HAVE___BUILTIN_EXPECT = 1,
        .HAVE___BUILTIN_PREFETCH = 1,
        .HAVE___CPU_TO_BE16 = null,
        .HAVE___CPU_TO_BE64 = null,
        .HAVE___CPU_TO_LE16 = null,
        .HAVE___CPU_TO_LE32 = null,
        .HAVE___CPU_TO_LE64 = null,
        .LDFLAGS_WL_AS_NEEDED = 1,
        .LDFLAGS_WL_GC_SECTIONS = 1,
        .PACKAGE_BUGREPORT = "https://github.com/allyourcodebase/nasm",
        .PACKAGE_NAME = "",
        .PACKAGE_STRING = "",
        .PACKAGE_TARNAME = "",
        .PACKAGE_URL = "",
        .PACKAGE_VERSION = "",
        .STDC_HEADERS = 1,
        ._ALL_SOURCE = 1,
        ._DARWIN_C_SOURCE = 1,
        .__EXTENSIONS__ = 1,
        ._GNU_SOURCE = 1,
        ._HPUX_ALT_XOPEN_SOCKET_API = 1,
        ._MINIX = null,
        ._NETBSD_SOURCE = 1,
        ._OPENBSD_SOURCE = 1,
        ._POSIX_SOURCE = null,
        ._POSIX_1_SOURCE = null,
        ._POSIX_PTHREAD_SEMANTICS = 1,
        .__STDC_WANT_IEC_60559_ATTRIBS_EXT__ = 1,
        .__STDC_WANT_IEC_60559_BFP_EXT__ = 1,
        .__STDC_WANT_IEC_60559_DFP_EXT__ = 1,
        .__STDC_WANT_IEC_60559_EXT__ = 1,
        .__STDC_WANT_IEC_60559_FUNCS_EXT__ = 1,
        .__STDC_WANT_IEC_60559_TYPES_EXT__ = 1,
        .__STDC_WANT_LIB_EXT2__ = 1,
        .__STDC_WANT_MATH_SPEC_FUNCS__ = 1,
        ._TANDEM_SOURCE = 1,
        ._XOPEN_SOURCE = null,
        .WORDS_BIGENDIAN = have(t.cpu.arch.endian() == .big),
        .WORDS_LITTLEENDIAN = have(t.cpu.arch.endian() != .big),
        ._FILE_OFFSET_BITS = null,
        ._FLTO_AUTO_FLTO = null,
        ._LARGEFILE_SOURCE = null,
        ._LARGE_FILES = null,
        ._TIME_BITS = null,
        .__MINGW_USE_VC2005_COMPAT = null,
        .__func__ = null,
        .@"const" = null,
        .@"inline" = null,
        .restrict = .__restrict__,
        .size_t = null,
        .snprintf = null,
        .typeof = null,
        .uintmax_t = null,
        .uintptr_t = null,
        .vsnprintf = null,
    }));
    const files = [_][]const u8{
        "nasmlib/alloc.c",
        "nasmlib/asprintf.c",
        "nasmlib/badenum.c",
        "nasmlib/bsi.c",
        "nasmlib/crc32b.c",
        "nasmlib/crc64.c",
        "nasmlib/file.c",
        "nasmlib/filename.c",
        "nasmlib/hashtbl.c",
        "nasmlib/ilog2.c",
        "nasmlib/md5c.c",
        "nasmlib/mmap.c",
        "nasmlib/numstr.c",
        "nasmlib/nctype.c",
        "nasmlib/path.c",
        "nasmlib/perfhash.c",
        "nasmlib/raa.c",
        "nasmlib/rbtree.c",
        "nasmlib/readnum.c",
        "nasmlib/realpath.c",
        "nasmlib/rlimit.c",
        "nasmlib/saa.c",
        "nasmlib/string.c",
        "nasmlib/strlist.c",
        "nasmlib/ver.c",
        "nasmlib/zerobuf.c",

        "asm/assemble.c",
        "asm/directbl.c",
        "asm/directiv.c",
        "asm/error.c",
        "asm/eval.c",
        "asm/exprdump.c",
        "asm/exprlib.c",
        "asm/floats.c",
        "asm/getbool.c",
        "asm/labels.c",
        "asm/listing.c",
        "asm/nasm.c",
        "asm/parser.c",
        "asm/pptok.c",
        "asm/pragma.c",
        "asm/preproc.c",
        "asm/quote.c",
        "asm/rdstrnum.c",
        "asm/segalloc.c",
        "asm/srcfile.c",
        "asm/stdscan.c",
        "asm/strfunc.c",
        "asm/tokhash.c",
        "asm/uncompress.c",
        "asm/warnings.c",

        "stdlib/snprintf.c",
        "stdlib/strlcpy.c",
        "stdlib/strnlen.c",
        "stdlib/strrchrnul.c",
        "stdlib/vsnprintf.c",

        "x86/iflag.c",
        "x86/insnsa.c",
        "x86/insnsb.c",
        "x86/insnsd.c",
        "x86/insnsn.c",
        "x86/regflags.c",
        "x86/regs.c",
        "x86/regvals.c",

        "common/common.c",

        "macros/macros.c",

        "output/codeview.c",
        "output/nulldbg.c",
        "output/nullout.c",
        "output/outaout.c",
        "output/outas86.c",
        "output/outbin.c",
        "output/outcoff.c",
        "output/outdbg.c",
        "output/outelf.c",
        "output/outform.c",
        "output/outieee.c",
        "output/outlib.c",
        "output/outmacho.c",
        "output/outobj.c",
    };
    const flags = [_][]const u8{
        "-DHAVE_CONFIG_H",
        "-std=c23",
        "-Wno-implicit-function-declaration",
    };
    exe.root_module.addCSourceFiles(.{
        .files = &files,
        .flags = &flags,
    });
    b.installArtifact(exe);
}

fn have(c: bool) ?c_int {
    return if (c) 1 else null;
}
